export const menuInformes = {
    "Informes": { icono: "fichero" },
    "Informes/Repeticiones": { url: "/InformeRepeticiones", regla: "sh_informes" },
    "Informes/Pedidos": { url: "/InformePedidosXAgente", regla: "sh_informes" },
    "Informes/Clientes por artículo": { url: "/informe-clientes-venta-art", regla: "sh_informes" },
    "Informes/Consumo por cliente": { url: "/informe-consumo-cliente", regla: "sh_informes" },
    "Informes/Ventas por artículo": { url: "/informe-ventas-articulo", regla: "sh_informes" },
    "Informes/Ventas por familia": { url: "/informe-ventas-familia", regla: "sh_informes" },
    "Informes/Ventas por población": { url: "/informe-ventas-poblacion", regla: "sh_informes" },
    "Informes/Tratos por agente": { url: "/informe-tratos-agente", regla: "sh_informes" },
    "Informes/Contactos por agente": { url: "/informe-contactos-agente", regla: "sh_informes" },
    "Informes/Geolocalización de clientes": { url: "/informe-mapa", regla: "sh_informes" },
    "Informes/Pedidos y líneas": { url: "/informe-ventas-pedidos", regla: "sh_informes" },
    "Informes/Clientes comparativa": { url: "/informe-clientes-comparativa", regla: "sh_informes" },
    "Informes/Clientes inactivos": { url: "/informe-clientes-inactivos", regla: "sh_informes" },
    "Informes/Clientes nuevos": { url: "/informe-clientes-nuevos", regla: "sh_informes" },
    "Informes/Tareas por agente": { url: "/informe-tareas-agente", regla: "sh_informes/marketing" },
    "Informes/Productos a caducar": { url: "/informes/productosacaducar", regla: "articulos/acceso_caducidad" },
};
