import {
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconArrowBack,
  IconArrowBackUp,
  IconArrowBarRight,
  IconArrowForwardUp,
  IconBackground,
  IconBasketDown,
  IconBuildingStore,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarMonth,
  IconCalendarWeek,
  IconChartBar,
  IconCheck,
  IconCheckbox,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleFilled,
  IconCirclePlus,
  IconCircleX,
  IconClockHour3,
  IconCopy,
  IconCreditCard,
  IconDeviceFloppy,
  IconEdit,
  IconEye,
  IconFile,
  IconHome,
  IconHourglass,
  IconLink,
  IconList,
  IconListDetails,
  IconLock,
  IconLockOpen,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMinus,
  IconPackage,
  IconPackageExport,
  IconPackageImport,
  IconPencil,
  IconPhone,
  IconPlayerPause,
  IconPlayerPauseFilled,
  IconPlus,
  IconQuestionMark,
  IconSearch,
  IconSettings,
  IconShoppingBag,
  IconShoppingCart,
  IconStackBack,
  IconStackBackward,
  IconStar,
  IconTable,
  IconTag,
  IconTool,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUsers,
  IconUserSearch,
  IconUsersGroup,
  IconX,
  type Icon,
} from "@tabler/icons-react";
import "./qicono.css";

type QIconoProps = {
  nombre: string;
  tamaño?: "xs" | "sm" | "md" | "lg" | "xl";
  color?: string;
  style?: React.CSSProperties;
};

const tamaños: Record<string, number> = {
  xs: 12,
  sm: 16,
  md: 20,
  lg: 28,
  xl: 40,
};

// https://tabler.io/icons
const iconos: Record<string, Icon> = {
  añadir: IconCirclePlus,
  buscar: IconSearch,
  "pendiente-nrj": IconBackground,
  "parcial-nrj": IconStackBackward,
  "preparado-nrj": IconStackBack,
  "para-enviar-nrj": IconPackage,
  "enviado-nrj": IconPackage,
  cerrar: IconX,
  inicio: IconHome,
  fichero: IconFile,
  grafico_barras: IconChartBar,
  candado: IconLock,
  candado_abierto: IconLockOpen,
  editar: IconEdit,
  editar_2: IconPencil,
  eliminar: IconTrash,
  guardar: IconDeviceFloppy,
  copiar: IconCopy,
  usuario: IconUser,
  perfil: IconUser,
  grupo: IconUsersGroup,
  cerrar_sesion: IconLogout,
  verdadero: IconCheck,
  falso: IconX,
  atras: IconArrowBack,
  adelante: IconArrowBarRight,
  deshacer: IconArrowBackUp,
  rehacer: IconArrowForwardUp,
  enlace: IconLink,
  alinear_izquierda: IconAlignLeft,
  alinear_centro: IconAlignCenter,
  alinear_derecha: IconAlignRight,
  menu: IconMenu2,
  calendario_vacio: IconCalendar,
  check: IconCheck,
  checkdoble: IconChecks,
  x_circle: IconCircleX,
  minus: IconMinus,
  lista: IconList,
  carrito: IconShoppingCart,
  tarjeta: IconCreditCard,
  etiqueta_compra: IconTag,
  llave_inglesa: IconTool,
  llaveinglesa: IconTool,
  ver: IconEye,
  crear: IconPlus,
  tabla: IconTable,
  arriba: IconChevronUp,
  abajo: IconChevronDown,
  izquierda: IconChevronLeft,
  derecha: IconChevronRight,
  circulo: IconCircle,
  circulo_relleno: IconCircleFilled,
  telefono: IconPhone,
  correo: IconMail,
  casa: IconHome,
  tarea: IconCheckbox,
  estrella: IconStar,
  relojarena: IconHourglass,
  ajustes: IconSettings,
  bolsa: IconShoppingBag,
  calendario_evento: IconCalendarEvent,
  calendario_mes: IconCalendarMonth,
  calendario_semana: IconCalendarWeek,
  paquete: IconPackage,
  paquete_import: IconPackageImport,
  paquete_export: IconPackageExport,
  usuario_circle: IconUserCircle,
  usuario_search: IconUserSearch,
  lista_detalle: IconListDetails,
  clock_3: IconClockHour3,
  tienda: IconBuildingStore,
  usuarios: IconUsers,
  pausa: IconPlayerPause,
  pausa_relleno: IconPlayerPauseFilled,
  devolucion: IconBasketDown,
};

export const QIcono = ({
  nombre,
  tamaño = "md",
  color,
  style,
}: QIconoProps) => {
  const Icono = iconos[nombre] ?? IconQuestionMark;
  const size = tamaños[tamaño] ?? 20;

  return (
    <quimera-icono>
      <Icono size={size} color={color} style={style} />
    </quimera-icono>
  );
};
