export enum ColorVariant {
  Primary = "primary",
  PrimaryDark = "primary-dark",
  PrimaryDarker = "primary-darker",
  PrimaryLight = "primary-light",
  PrimaryLighter = "primary-lighter",
  Success = "success",
  SuccessDark = "success-dark",
  SuccessDarker = "success-darker",
  SuccessLight = "success-light",
  SuccessLighter = "success-lighter",
  Danger = "danger",
  DangerDark = "danger-dark",
  DangerDarker = "danger-darker",
  DangerLight = "danger-light",
  DangerLighter = "danger-lighter",
}
