import { Entidad } from "@olula/lib/diseño.ts";

export interface Evento extends Entidad {
    evento_id: string;
    id: string; // Alias para evento_id para compatibilidad con Detalle
    altas_ss: boolean;
    camerinos: boolean;
    camion_escenario: boolean;
    carteleria: boolean;
    ccf: string | null;
    cliente_id: string | null;
    nombre_cliente: string | null;
    codproyecto: string | null;
    conexion_electrica: string | null;
    descripcion: string | null;
    descripcion_ref: string | null;
    direccion: string | null;
    enviado_a_cliente: boolean;
    enviado_a_proveedor: boolean;
    empresa_id: number | null;
    nombre_empresa: string | null;
    estado_id: string | null;
    factura_enviada: boolean;
    fecha_inicio: string | null;
    gastos_facturacion: number | null;
    gastos_personal: number | null;
    hora_inicio: string | null;
    hora_montaje: string | null;
    hora_prueba_sonido: string | null;
    hoja_ruta_enviada: boolean;
    hoja_ruta_hecha: boolean;
    liquidacion: boolean;
    lugar: string | null;
    num_descansos: number | null;
    observaciones: string | null;
    organizador_evento: string | null;
    presupuesto: boolean;
    proveedor_id: string | null;
    nombre_proveedor: string | null;
    recibido_por_cliente: boolean;
    referencia: string | null;
    responsable_local: string | null;
    responsable_orquesta: string | null;
    responsable_producciones: string | null;
    recibido_por_proveedor: boolean;
    subtotal_coste: number | null;
    telefono: string | null;
    tipo_escenario: string | null;
    total_beneficio: number | null;
    total_costes: number | null;
    total_costesind: number | null;
    total_ingresos: number | null;
};

export type NuevoEvento = {
    altas_ss: boolean;
    camerinos: boolean;
    camion_escenario: boolean;
    carteleria: boolean;
    ccf: string;
    cliente_id: string;
    codproyecto: string;
    conexion_electrica: string;
    descripcion: string;
    descripcion_ref: string;
    direccion: string;
    enviado_a_cliente: boolean;
    enviado_a_proveedor: boolean;
    empresa_id: number;
    estado_id: string;
    factura_enviada: boolean;
    fecha_inicio: string;
    gastos_facturacion: number;
    gastos_personal: number;
    hora_inicio: string;
    hora_montaje: string;
    hora_prueba_sonido: string;
    hoja_ruta_enviada: boolean;
    hoja_ruta_hecha: boolean;
    liquidacion: boolean;
    lugar: string;
    num_descansos: number;
    observaciones: string;
    organizador_evento: string;
    presupuesto: boolean;
    proveedor_id: string;
    recibido_por_cliente: boolean;
    referencia: string;
    responsable_local: string;
    responsable_orquesta: string;
    responsable_producciones: string;
    recibido_por_proveedor: boolean;
    subtotal_coste: number;
    telefono: string;
    tipo_escenario: string;
    total_beneficio: number;
    total_costes: number;
    total_costesind: number;
    total_ingresos: number;
};