const initialData = {
  tiposGenero: [
    { key: "Hombre", value: "Hombre" },
    { key: "Mujer", value: "Mujer" },
    { key: "Otro", value: "Otro" },
  ],
  provincias: [
    { key: 1, value: "ALAVA" },
    { key: 2, value: "ALBACETE" },
    { key: 3, value: "ALICANTE" },
    { key: 4, value: "ALMERIA" },
    { key: 5, value: "ASTURIAS" },
    { key: 6, value: "AVILA" },
    { key: 7, value: "BADAJOZ" },
    { key: 8, value: "BALEARES" },
    { key: 9, value: "BARCELONA" },
    { key: 10, value: "BURGOS" },
    { key: 11, value: "CACERES" },
    { key: 12, value: "CADIZ" },
    { key: 13, value: "CANTABRIA" },
    { key: 14, value: "CASTELLON" },
    { key: 15, value: "CIUDAD REAL" },
    { key: 16, value: "CORDOBA" },
    { key: 17, value: "LA CORUÑA" },
    { key: 18, value: "CUENCA" },
    { key: 19, value: "GERONA" },
    { key: 20, value: "GRANADA" },
    { key: 21, value: "GUADALAJARA" },
    { key: 22, value: "GUIPUZCOA" },
    { key: 23, value: "HUELVA" },
    { key: 24, value: "HUESCA" },
    { key: 25, value: "JAEN" },
    { key: 26, value: "LEON" },
    { key: 27, value: "LERIDA" },
    { key: 28, value: "LUGO" },
    { key: 29, value: "MADRID" },
    { key: 30, value: "MALAGA" },
    { key: 31, value: "MURCIA" },
    { key: 32, value: "NAVARRA" },
    { key: 33, value: "ORENSE" },
    { key: 34, value: "PALENCIA" },
    { key: 35, value: "LAS PALMAS" },
    { key: 36, value: "PONTEVEDRA" },
    { key: 37, value: "LA RIOJA" },
    { key: 38, value: "SALAMANCA" },
    { key: 39, value: "SEGOVIA" },
    { key: 40, value: "SEVILLA" },
    { key: 41, value: "SORIA" },
    { key: 42, value: "TARRAGONA" },
    { key: 43, value: "SANTA CRUZ DE TENERIFE" },
    { key: 44, value: "TERUEL" },
    { key: 45, value: "TOLEDO" },
    { key: 46, value: "VALENCIA" },
    { key: 47, value: "VALLADOLID" },
    { key: 48, value: "VIZCAYA" },
    { key: 49, value: "ZAMORA" },
    { key: 50, value: "ZARAGOZA" },
    { key: 51, value: "CEUTA" },
    { key: 52, value: "MELILLA" },
  ],
};

export default initialData;
