export const menuSmartsales = {
    "SmartSales": { icono: "fichero" },
    "SmartSales/Dashboard": { url: "/ss/dashboard", regla: "crm.trato" },
    "SmartSales/Tipos de trato": { url: "/ss/tipostrato", regla: "crm.campana.leer" },
    "SmartSales/Business Intelligence": { url: "/ss/bi", regla: "crm.informe.bi" },
    "SmartSales/Campañas": { url: "/ss/campanias", regla: "crm.campana.leer" },
    "SmartSales/Lead Pacientes": { url: "/ss/leadpacientes", regla: "lead_pacientes:visit" },
    "SmartSales/Tratos": { url: "/ss/tratos", regla: "crm.trato.leer" },
    "SmartSales/Farma": { url: "/ss/tratosfarma", regla: "crm.trato.farma" },
    // "SmartSales/Licencias": { url: "/ss/licencias" },
    "SmartSales/Contactos": { url: "/ss/contactosmd", regla: "crm.campana.leer" },
    "SmartSales/Cursos": { url: "/ss/cursos", regla: "crm.trato" },
    "SmartSales/Clientes": { url: "/ss/clientes", regla: "crm.cliente.acceso_clientes" },
    "SmartSales/Incidencias": { url: "/ss/incidencias" },
};
