import { Grupo, Regla } from "./diseño.ts";

export const grupos: Grupo[] = [
  {
    id: "Administracion",
    descripcion: "Administadores",
  },
  {
    id: "Almacen",
    descripcion: "Almacen",
  },
  {
    id: "calidad",
    descripcion: "Responsable de calidad",
  },
  {
    id: "gerentes",
    descripcion: "Gerentes",
  },
  {
    id: "MKT",
    descripcion: "Marketing",
  },
  {
    id: "Oficina",
    descripcion: "Oficinas",
  },
];

export const rules: Regla[] = [
  {
    eventos: [],
    id: "general",
    grupo: "general",
    descripcion: "General",
  },
  {
    eventos: [],
    id: "contabilidad.asiento",
    grupo: "contabilidad.asiento",
    descripcion: "Contabilidad - Asiento",
  },
  {
    eventos: [],
    id: "contabilidad.subcuentas_cliente",
    grupo: "contabilidad.subcuentas_cliente",
    descripcion: "Contabilidad - Subcuentas_cliente",
  },
  {
    eventos: [],
    id: "ventas.pedido",
    grupo: "ventas.pedido",
    descripcion: "Ventas - Pedido",
  },
  {
    eventos: [],
    id: "ventas.pedido.leer",
    grupo: "ventas.pedido",
    descripcion: "Ventas - Pedido - Leer",
  },
  {
    eventos: [],
    id: "ventas.pedido.crear",
    grupo: "ventas.pedido",
    descripcion: "Ventas - Pedido - Crear",
  },
  {
    eventos: [],
    id: "ventas.pedido.borrar",
    grupo: "ventas.pedido",
    descripcion: "Ventas - Pedido - Borrar",
  },
  {
    eventos: [],
    id: "publica",
    grupo: "publica",
    descripcion: "Publica",
  },
  {
    eventos: [],
    id: "administracion",
    grupo: "administracion",
    descripcion: "Administracion",
  },
  {
    eventos: [],
    id: "comun.evento_cola",
    grupo: "comun.evento_cola",
    descripcion: "Comun - Evento_cola",
  },
  {
    eventos: [],
    id: "comun.ejercicio_facturacion",
    grupo: "comun.ejercicio_facturacion",
    descripcion: "Comun - Ejercicio_facturacion",
  },
  {
    eventos: [],
    id: "almacen.reserva_composicion",
    grupo: "almacen.reserva_composicion",
    descripcion: "Almacen - Reserva_composicion",
  },
  {
    eventos: [],
    id: "almacen.lote",
    grupo: "almacen.lote",
    descripcion: "Almacen - Lote",
  },
  {
    eventos: [],
    id: "almacen.stock_reservado",
    grupo: "almacen.stock_reservado",
    descripcion: "Almacen - Stock_reservado",
  },
  {
    eventos: [],
    id: "almacen.prevision_asiento",
    grupo: "almacen.prevision_asiento",
    descripcion: "Almacen - Prevision_asiento",
  },
  {
    eventos: [],
    id: "almacen.articulo",
    grupo: "almacen.articulo",
    descripcion: "Almacen - Articulo",
  },
  {
    eventos: [],
    id: "almacen.stock",
    grupo: "almacen.stock",
    descripcion: "Almacen - Stock",
  },
  {
    eventos: [],
    id: "almacen.albaran_salida",
    grupo: "almacen.albaran_salida",
    descripcion: "Almacen - Albaran_salida",
  },
  {
    eventos: [],
    id: "tesoreria.cliente",
    grupo: "tesoreria.cliente",
    descripcion: "Tesoreria - Cliente",
  },
  {
    eventos: [],
    id: "crm.contacto",
    grupo: "crm.contacto",
    descripcion: "Crm - Contacto",
  },
  {
    eventos: [],
    id: "crm.estado_oportunidad_venta",
    grupo: "crm.estado_oportunidad_venta",
    descripcion: "Crm - Estado_oportunidad_venta",
  },
  {
    eventos: [],
    id: "crm.oportunidad_venta",
    grupo: "crm.oportunidad_venta",
    descripcion: "Crm - Oportunidad_venta",
  },
  {
    eventos: [],
    id: "crm.estado_lead",
    grupo: "crm.estado_lead",
    descripcion: "Crm - Estado_lead",
  },
  {
    eventos: [],
    id: "crm.cliente",
    grupo: "crm.cliente",
    descripcion: "Crm - Cliente",
  },
  {
    eventos: [],
    id: "crm.lead",
    grupo: "crm.lead",
    descripcion: "Crm - Lead",
  },
  {
    eventos: [],
    id: "crm.accion",
    grupo: "crm.accion",
    descripcion: "Crm - Accion",
  },
  {
    eventos: [],
    id: "crm.fuente_lead",
    grupo: "crm.fuente_lead",
    descripcion: "Crm - Fuente_lead",
  },
  {
    eventos: [],
    id: "ventas.albaran",
    grupo: "ventas.albaran",
    descripcion: "Ventas - Albaran",
  },
  {
    eventos: [],
    id: "ventas.albaran.crear",
    grupo: "ventas.albaran",
    descripcion: "Ventas - Albaran - Crear",
  },
  {
    eventos: [],
    id: "ventas.albaran.borrar",
    grupo: "ventas.albaran",
    descripcion: "Ventas - Albaran - Borrar",
  },
  {
    eventos: [],
    id: "ventas.factura",
    grupo: "ventas.factura",
    descripcion: "Ventas - Factura",
  },
  {
    eventos: [],
    id: "ventas.presupuesto",
    grupo: "ventas.presupuesto",
    descripcion: "Ventas - Presupuesto",
  },
  {
    eventos: [],
    id: "ventas.cliente",
    grupo: "ventas.cliente",
    descripcion: "Ventas - Cliente",
  },
  {
    eventos: [],
    id: "ventas.direcciones_cliente",
    grupo: "ventas.direcciones_cliente",
    descripcion: "Ventas - Direcciones_cliente",
  },
  {
    eventos: [],
    id: "ventas.cuentas_banco_cliente",
    grupo: "ventas.cuentas_banco_cliente",
    descripcion: "Ventas - Cuentas_banco_cliente",
  },
  {
    eventos: [],
    id: "auth.regla.leer",
    grupo: "auth.regla",
    descripcion: "Auth - Regla - Leer",
  },
  {
    eventos: [],
    id: "almacen.stocks",
    grupo: "almacen.stocks",
    descripcion: "Almacen - Stocks",
  },
  {
    eventos: [],
    id: "contexto.recibo_venta",
    grupo: "contexto.recibo_venta",
    descripcion: "Contexto - Recibo_venta",
  },
  {
    eventos: [],
    id: "crm.estados_oportunidad_venta",
    grupo: "crm.estados_oportunidad_venta",
    descripcion: "Crm - Estados_oportunidad_venta",
  },
  {
    eventos: [],
    id: "crm.acciones",
    grupo: "crm.acciones",
    descripcion: "Crm - Acciones",
  },
  {
    eventos: [],
    id: "crm.clientes",
    grupo: "crm.clientes",
    descripcion: "Crm - Clientes",
  },
  {
    eventos: [],
    id: "crm.contactos",
    grupo: "crm.contactos",
    descripcion: "Crm - Contactos",
  },
  {
    eventos: [],
    id: "crm.oportunidades_venta",
    grupo: "crm.oportunidades_venta",
    descripcion: "Crm - Oportunidades_venta",
  },
  {
    eventos: [],
    id: "crm.oportunidades_por_cliente",
    grupo: "crm.oportunidades_por_cliente",
    descripcion: "Crm - Oportunidades_por_cliente",
  },
  {
    eventos: [],
    id: "crm.agente",
    grupo: "crm.agente",
    descripcion: "Crm - Agente",
  },
  {
    eventos: [],
    id: "ventas.articulo",
    grupo: "ventas.articulo",
    descripcion: "Ventas - Articulo",
  },
  {
    eventos: [],
    id: "crm.direccion_cliente",
    grupo: "crm.direccion_cliente",
    descripcion: "Crm - Direccion_cliente",
  },
  {
    eventos: [],
    id: "crm.direcciones_cliente",
    grupo: "crm.direcciones_cliente",
    descripcion: "Crm - Direcciones_cliente",
  },
  {
    eventos: [],
    id: "ventas.cuenta_banco_cliente",
    grupo: "ventas.cuenta_banco_cliente",
    descripcion: "Ventas - Cuenta_banco_cliente",
  },
];

export const permisos = [
  {
    idpermission: 2,
    idrule: "general",
    id: "almacen",
    value: false,
  },
  {
    idpermission: 3,
    idrule: "albaranescli/delete",
    id: "almacen",
    value: false,
  },
  {
    idpermission: 59,
    idrule: "presupuestoscli",
    id: "almacen",
    value: true,
  },
  {
    idpermission: 60,
    idrule: "presupuestoscli",
    id: "administracion",
    value: false,
  },
  {
    idpermission: 61,
    idrule: "presupuestoscli/delete",
    id: "almacen",
    value: false,
  },
];
