export { parsearNumeroVoz } from "./parsearNumeroVoz.ts";
export { useReconocimientoVoz } from "./useReconocimientoVoz.ts";
export type { UseReconocimientoVoz } from "./useReconocimientoVoz.ts";
export { useSintesisVoz } from "./useSintesisVoz.ts";
export type { UseSintesisVoz } from "./useSintesisVoz.ts";
export { useFlujoVoz } from "./useFlujoVoz.ts";
export type { PreguntaVoz, TipoRespuesta, EstadoFlujoVoz, UseFlujoVoz, ValorVoz } from "./useFlujoVoz.ts";
export { useEscuchaContinua, reconocimientoContinuoSoportado } from "./useEscuchaContinua.ts";
export type { ResultadoEscucha, UseEscuchaContinua } from "./useEscuchaContinua.ts";
export { useNivelMicro } from "./useNivelMicro.ts";
export { reproducirTono } from "./tonos.ts";
export { useModoVozActivo, modoVozActivo, establecerModoVoz } from "./modo_voz.ts";
export { separarFrases, crearLectorFrases } from "./lector_frases.ts";
export type { LectorFrases } from "./lector_frases.ts";
export { grabarFrase, grabacionSoportada, evaluarVad, iniciarVad, VAD_POR_DEFECTO } from "./grabar_frase.ts";
export type { AudioGrabado, OpcionesVad, EstadoVad, DecisionVad } from "./grabar_frase.ts";
export type { DetectorActivacion } from "./detector_activacion.ts";
export { modoCapturaVoz } from "./modo_voz.ts";
export type { ModoCapturaVoz } from "./modo_voz.ts";
export { reservarVoz, vozOcupada, useVozOcupada } from "./voz_ocupada.ts";
export { normalizarParaVoz } from "./normalizar_voz.ts";
export { useBotonAuricular, botonAuricularSoportado } from "./useBotonAuricular.ts";
export { normalizarImportesDictados } from "./importes_dictados.ts";
